### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by codepraycode** [nobox-org/nobox-js-client#1]
When using this function in the Nobox instance *Nobox.login({ email, password })* 

In VsCode, typescript extension was indicating this
```
Argument of type '{ email: string; password: string; }' is not assignable to parameter of type 'Omit<LoginArgs<unknown>, "config">'.
  Object literal may only specify known properties, and 'email' does not exist in type 'Omit<LoginArgs<unknown>, "config">'.ts(2345)
```
and in the terminal, I was getting this

```
C:\Users\USER\projects\...\node_modules\nobox-client\lib\utils.js:53
    var structure = _a.structure, space = _a.space, description = _a.description, authOptions = _a.authOptions, functionOptions = _a.functionOptions, clear = _a.clear, initialData = _a.initialData, webhooks = _a.webhooks;
                       ^
TypeError: Cannot read properties of undefined (reading 'structure')
    at reMapSpaceStructureForCreation (C:\Users\USER\projects\...\node_modules\nobox-client\lib\utils.js:53:24)
    at C:\Users\USER\projects\...\node_modules\nobox-client\lib\functions\login.js:56:77
    at step (C:\Users\USER\projects\...\node_modules\nobox-client\lib\functions\login.js:33:23)
    at Object.next (C:\Users\USER\projects\...\node_modules\nobox-client\lib\functions\login.js:14:53)
    at C:\Users\USER\projects\...\node_modules\nobox-client\lib\functions\login.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\USER\projects\...\node_modules\nobox-client\lib\functions\login.js:4:12)
    at _login (C:\Users\USER\projects\...\node_modules\nobox-client\lib\functions\login.js:49:39)
    at Object.<anonymous> (C:\Users\USER\projects\...\node_modules\nobox-client\lib\functions\get-functions.js:65:58)
    at step (C:\Users\USER\projects\...\node_modules\nobox-client\lib\functions\get-functions.js:44:23)

```

## Steps to reproduce

Basically following the login procedure in the [doc](https://www.docs.nobox.cloud/functions/login)

**Comment by Akintunde102** [comment]
Working on it. I will get back once it is reproduced and fixed.

**Comment by Akintunde102** [comment]
Already fixed. So closing
